apiVersion: 1

# Just one datasource is needed for this project: PostgreSQL
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db.:5432  # Same port as in docker-compose.yaml
    database: test
    user: postgres
    secureJsonData:
      password: 'example'  # Same password as in docker-compose.yaml
    jsonData:
      sslmode: 'disable'
